version: '3.9'

services:
  front:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
  api:

    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
